version: '3.8'

services:
  web:
    image: igor2022/clockbox
    command: python manage.py runserver 0.0.0.0:8080

    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_date:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_date:


