# Generated by Django 4.1.2 on 2022-10-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("big", models.IntegerField()),
                ("author_bid", models.CharField(max_length=64)),
                ("date_bid", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auction_name", models.CharField(max_length=64)),
                ("comments", models.TextField()),
                ("author_comments", models.CharField(max_length=64)),
                ("date_comm", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categor", models.CharField(max_length=40)),
                ("product_name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("author_auct", models.CharField(max_length=64)),
                ("active", models.BooleanField()),
                ("commet", models.ManyToManyField(blank=True, to="auctions.comments")),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auctions.bid"
                    ),
                ),
            ],
        ),
    ]
