# Generated by Django 4.1.2 on 2022-10-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comments_auction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="auction",
            name="categor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.category"
            ),
        ),
    ]
