# Generated by Django 4.1.2 on 2022-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="brief_descrip",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="auction",
            name="name",
            field=models.CharField(default="", max_length=64, unique=True),
        ),
    ]
