# Generated by Django 4.1.2 on 2022-10-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auction_brief_descrip_alter_auction_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="big",
            new_name="bid",
        ),
    ]
