# Generated by Django 4.1.2 on 2022-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_rename_big_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comments",
            field=models.TextField(verbose_name="Add comments"),
        ),
    ]
