# Generated by Django 4.1.2 on 2022-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_comments_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image1",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="auction",
            name="image2",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="auction",
            name="image3",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="brief_descrip",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
