# Generated by Django 4.1.2 on 2022-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_auction_image1_auction_image2_auction_image3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo.jpeg",
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image1",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo.jpeg",
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image2",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo.jpeg",
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image3",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo.jpeg",
                upload_to="media",
            ),
        ),
    ]
