# Generated by Django 4.1.2 on 2022-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_auction_image_alter_auction_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image1",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo1.jpeg",
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image2",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo2.jpeg",
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image3",
            field=models.ImageField(
                blank=True,
                default="/static/img/media/not_photo3.jpeg",
                upload_to="media",
            ),
        ),
    ]
