# Generated by Django 4.1.2 on 2022-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auction_image1_alter_auction_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True, default="not_photo.jpeg", upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image1",
            field=models.ImageField(
                blank=True, default="not_photo1.jpeg", upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image2",
            field=models.ImageField(
                blank=True, default="not_photo2.jpeg", upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image3",
            field=models.ImageField(
                blank=True, default="not_photo3.jpeg", upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="name",
            field=models.CharField(
                default="",
                help_text="This field must be unique",
                max_length=64,
                unique=True,
            ),
        ),
    ]
