# Generated by Django 4.1.2 on 2022-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_transaction_item_namex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="address_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
