# Generated by Django 4.1.2 on 2022-12-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_alter_transaction_address_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="item_namex",
            new_name="item_name",
        ),
    ]
