# Generated by Django 4.1.2 on 2022-12-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_transaction_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="contact_phone",
            field=models.CharField(max_length=20),
        ),
    ]
