# Generated by Django 4.1.2 on 2022-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_transaction_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
